
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWd3qFnOPh8WmWN6AKn4NAqSs3TdZ7UE',
    iosBundleId: 'com.act3',
    appId: '1:954080229112:ios:dbd56a9c6062a4baed2d0d',
    storageBucket: 'act3-22702.appspot.com',
    messagingSenderId: '954080229112',
    iosClientId: 'undefined',
    projectId: 'act3-22702'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RqDaeDoqfXeBZa7Vqm3yqluV-HyQvQw',
    appId: '1:954080229112:android:eaf75729a704302ded2d0d',
    messagingSenderId: '954080229112',
    projectId: 'act3-22702',
    storageBucket: 'act3-22702.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5dgp0uHso5gwsFkWuDCNtI_-REhOyvfo',
    authDomain: 'act3-22702.firebaseapp.com',
    projectId: 'act3-22702',
    storageBucket: 'act3-22702.appspot.com',
    messagingSenderId: '954080229112',
    appId: '1:954080229112:web:36ff637293cf2788ed2d0d'
  );
}
